# Generated by Django 5.2.7 on 2025-10-27 20:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_equipement_parts_equipement_teams_in_charge_and_more'),
        ('core', '0002_location_manufacturer_assetmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('barcode', models.CharField(blank=True, default='', help_text='QR/Barcode text', max_length=128)),
                ('part_number', models.CharField(blank=True, default='', help_text='Internal SKU', max_length=64)),
                ('unit', models.CharField(choices=[('GENERAL', 'General'), ('PCS', 'Pieces'), ('M', 'Meters'), ('L', 'Liters'), ('KG', 'Kilograms')], default='GENERAL', max_length=16)),
                ('units_in_stock', models.PositiveIntegerField(default=0)),
                ('minimum_in_stock', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assets', models.ManyToManyField(blank=True, related_name='inventory_parts', to='assets.equipement')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_parts', to='core.location')),
                ('types', models.ManyToManyField(blank=True, related_name='parts', to='inventory.parttype')),
                ('teams_in_charge', models.ManyToManyField(blank=True, related_name='parts', to='inventory.team')),
            ],
            options={
                'db_table': 'gmao_part',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PartVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_sku', models.CharField(blank=True, default='', max_length=64)),
                ('last_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_links', to='inventory.part')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_links', to='inventory.vendor')),
            ],
            options={
                'ordering': ('vendor__name',),
                'unique_together': {('part', 'vendor')},
            },
        ),
        migrations.AddField(
            model_name='part',
            name='vendors',
            field=models.ManyToManyField(related_name='parts', through='inventory.PartVendor', to='inventory.vendor'),
        ),
        migrations.CreateModel(
            name='PartFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='parts/')),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inventory.part')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
