# Generated by Django 5.2.7 on 2025-10-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_equipement_parts_equipement_teams_in_charge_and_more'),
        ('core', '0002_location_manufacturer_assetmodel'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['name'], name='gmao_part_name_6bf9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['slug'], name='gmao_part_slug_dc71a5_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['barcode'], name='gmao_part_barcode_955bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['part_number'], name='gmao_part_part_nu_954e84_idx'),
        ),
    ]
