# Generated by Django 5.2.7 on 2025-10-27 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=200, unique=True, verbose_name="Nom du lieu")),
            ],
            options={
                "verbose_name": "Localisation",
                "verbose_name_plural": "Localisations",
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=200, unique=True, verbose_name="Fabricant")),
            ],
            options={
                "verbose_name": "Fabricant",
                "verbose_name_plural": "Fabricants",
            },
        ),
        migrations.CreateModel(
            name="AssetModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=200, verbose_name="Modele")),
                (
                    "fabricant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modeles",
                        to="core.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modele d'equipement",
                "verbose_name_plural": "Modeles d'equipement",
                "unique_together": {("fabricant", "nom")},
            },
        ),
    ]
