# Generated by Django 5.2.7 on 2025-10-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='parts',
            field=models.CharField(blank=True, max_length=255, verbose_name='Parts'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='teams_in_charge',
            field=models.CharField(blank=True, max_length=255, verbose_name='Teams in charge'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='vendors',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vendors'),
        ),
    ]
